version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  seed:
    build:
      context: .
      dockerfile: seed/Dockerfile
    container_name: seed
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: "no" 

  ml-client:
    build:
      context: .
      dockerfile: machine_learning_client/Dockerfile
    container_name: ml-client
    env_file:
      - .env 
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    

  web-app:
    build:
      context: .
      dockerfile: web_app/Dockerfile
    container_name: web-app
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./web_app:/app
    depends_on:
      - seed
      - ml-client


volumes:
  mongodb_data:

